#! /home/data53/code/repos/useful_and_common_scripts/env/bin/python

from jose import jwt 
import sys

def decode_jwt(token: str):
    print("UNVERIFIED HEADER")
    print(jwt.get_unverified_header(token), '\n\n')

    print("UNVERIFIED PAYLOAD/CLAIMS")
    print(jwt.get_unverified_claims(token), '\n\n')
    
if __name__ == '__main__': 
    token = sys.argv[1]
    decode_jwt(token)


