#! /home/data53/code/repos/useful_and_common_scripts/env/bin/python

from jose import jwt 
import sys
import time 

def decode_jwt(token: str):
    print("UNVERIFIED HEADER")
    print(jwt.get_unverified_header(token), '\n\n')

    print("UNVERIFIED PAYLOAD/CLAIMS")
    unverified_claims = jwt.get_unverified_claims(token)
    print(unverified_claims, '\n\n')
    
    
    if 'exp' in unverified_claims.keys():
        print(f"EXPIRE DATE OF JWT TOKEN: {time.ctime(unverified_claims['exp'])}")


if __name__ == '__main__': 
    token = sys.argv[1]
    decode_jwt(token)


